resources:
- ../base
namePrefix: reapi-
images:
- name: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
  newName: ghcr.io/bharatradar/readsb
  newTag: latest
patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["--net-only", "--net", "--net-receiver-id", "--net-connector=hub-readsb,30005,beast_in", "--net-api-port=30152", "--device-type=none"]
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe
      value: null
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe
      value: null
    - op: replace
      path: /spec/template/spec/containers/0/startupProbe
      value: null
