resources:
- ../base
- flux.yaml
- nginx-config.yaml
commonLabels:
  name: mlat-map
patches:
- target:
    kind: Deployment
    name: mlat-map
  patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value:
        - name: nginx-conf
          configMap:
            name: mlat-map-nginx
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
