apiVersion: v1
kind: ConfigMap
metadata:
  name: mlat-map-nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      
      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }
      
      location /api/0/mlat-server/ {
        resolver 10.43.0.10 valid=5s;
        set $mlat_backend mlat-mlat-server.bharatradar.svc.cluster.local;
        rewrite ^/api/0/mlat-server/[^/]+/(.*)$ /$1 break;
        proxy_pass http://$mlat_backend:150;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
      }

      location /syncmap/api/0/mlat-server/ {
        resolver 10.43.0.10 valid=5s;
        set $mlat_backend mlat-mlat-server.bharatradar.svc.cluster.local;
        rewrite ^/syncmap/api/0/mlat-server/[^/]+/(.*)$ /$1 break;
        proxy_pass http://$mlat_backend:150;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
      }
    }
