resources:
- haproxy/default
- ingest/default
- external/default
- hub/default
- mlat/default  # ✅ adsblol/mlat-server works
- reapi/default
#- planes-default  # needs adsblol-rclone secret
- mlat-map/default
- api-default  
- history-default  # ✅ ragavellur/history forked
- redis/default
- resources.yaml
namespace: adsblol
images:
- name: ghcr.io/katlol/readsb
  newName: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf
  newTag: latest
- name: ghcr.io/katlol/mlat-server
  newName: ghcr.io/adsblol/mlat-server
  newTag: latest
- name: ghcr.io/sdr-enthusiasts/docker-tar1090
  newName: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf
  newTag: latest
- name: ghcr.io/adsblol/history
  newName: ghcr.io/ragavellur/history
  newTag: latest
- name: ghcr.io/katlol/mlat-server
  newName: ghcr.io/adsblol/mlat-server
  newTag: latest
- name: ghcr.io/sdr-enthusiasts/docker-tar1090
  newName: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf
  newTag: latest
