resources:
- haproxy/default
- ingest/default
- external/default
- hub/default
- mlat/default
- reapi/default
- planes/default
- mlat-map/default
- api/default
- history/default
- redis/default
- website/default
- resources.yaml
namespace: bharatradar
images:
- name: ghcr.io/adsblol/mlat-server
  newName: ghcr.io/bharatradar/mlat-server
  newTag: latest
- name: ghcr.io/ragavellur/history
  newName: ghcr.io/bharatradar/history
  newTag: latest
