resources:
- ../base
namePrefix: ingest-
commonLabels:
  service: public
images:
- name: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
  newName: ghcr.io/bharatradar/readsb
  newTag: latest
patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["--net-only", "--net", "--net-ingest", "--net-receiver-id", "--net-bi-port=30004", "--net-bo-port=30005", "--net-bind-address=0.0.0.0", "--device-type=none", "--max-range=99999"]
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe
      value: null
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe
      value: null
    - op: replace
      path: /spec/template/spec/containers/0/startupProbe
      value: null
