---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tar1090-config
data:
  config.js: |
    PageName = "ADSB.lol - Open Source ADSB/MLAT aggregator.";
    BingMapsAPIKey = "AqCdYNFHcAZuy4k9zT_UXZMdfSo5zN-mImkwN6PzcXNYyo0bYHaHik2F8qg-h1c1";
    shareBaseUrl = "https://map.bharat-radar.vellur.in";
